// src/components/DriveVideo/index.jsx
/* eslint-disable camelcase */
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { CircularProgress, Typography } from '@material-ui/core';
import ReactPlayer from 'react-player/file';

import { api } from '../../api/backend';

import Colors from '../../colors';
import { ErrorOutline } from '../../icons';
import { currentOffset, setVideoClock } from '../../timeline';
import { seek, bufferVideo, pause, play } from '../../timeline/playback';
import { isIos, isFirefox } from '../../utils/browser.js';

const VideoOverlay = ({ loading, error }) => {
  let content;
  if (error) {
    content = (
      <>
        <ErrorOutline className="mb-2" />
        <Typography>{error}</Typography>
      </>
    );
  } else if (loading) {
    content = <CircularProgress style={{ color: Colors.white }} thickness={4} size={50} />;
  } else {
    return null;
  }
  return (
    <div className="z-50 absolute h-full w-full bg-[#16181AAA]">
      <div className="relative text-center top-[calc(50%_-_25px)]">
        {content}
      </div>
    </div>
  );
};

class DriveVideo extends Component {
  constructor(props) {
    super(props);

    this.onVideoLoaded = this.onVideoLoaded.bind(this);
    this.onVideoProgress = this.onVideoProgress.bind(this);
    this.onVideoPause = this.onVideoPause.bind(this);
    this.onVideoPlay = this.onVideoPlay.bind(this);
    this.onVideoEnded = this.onVideoEnded.bind(this);
    this.onHlsError = this.onHlsError.bind(this);
    this.onVideoError = this.onVideoError.bind(this);
    this.onVideoBuffering = this.onVideoBuffering.bind(this);
    this.onVideoResume = this.onVideoResume.bind(this);
    this.videoOffset = this.videoOffset.bind(this);

    this.videoPlayer = React.createRef();
    this.video = null; // the <video> element, once it is the playback clock

    this.state = {
      src: null,
      videoError: null,
    };
  }

  componentDidMount() {
    this.props.dispatch(bufferVideo(true));
    this.updateVideoSource({});
  }

  componentDidUpdate(prevProps) {
    this.updateVideoSource(prevProps);

    // seeks land in redux, the video carries them out
    const { offset, startTime } = this.props;
    if (this.video && (prevProps.offset !== offset || prevProps.startTime !== startTime)) {
      this.seekVideo(offset);
    }
  }

  componentWillUnmount() {
    if (!this.video) {
      return;
    }
    // hand the clock back to redux so the map keeps playing without the video
    const offset = currentOffset();
    this.releaseVideo();
    this.props.dispatch(seek(offset));
    this.props.dispatch(bufferVideo(false));
  }

  // the duration is known once per source, the video can take over the clock
  onVideoLoaded() {
    const { currentRoute, dispatch } = this.props;
    const video = this.videoPlayer.current?.getInternalPlayer();
    if (this.video || !video || !currentRoute) {
      return;
    }
    video.currentTime = this.currentVideoTime();
    this.video = video;
    setVideoClock(currentRoute.fullname, this.videoOffset);
    dispatch(bufferVideo(false));
  }

  onVideoProgress() {
    const { dispatch, loop } = this.props;
    if (!this.video || !loop) {
      return;
    }
    const pastEnd = this.videoOffset() > loop.startTime + loop.duration;
    const beforeStart = this.currentVideoTime(loop.startTime) - this.video.currentTime > 0.5;
    if (pastEnd || beforeStart) {
      dispatch(seek(loop.startTime));
    }
  }

  // keep redux in step when the browser or OS pauses / resumes the video
  onVideoPause() {
    const { desiredPlaySpeed, dispatch } = this.props;
    if (desiredPlaySpeed && this.video && !this.video.ended) {
      dispatch(pause());
    }
  }

  onVideoPlay() {
    const { desiredPlaySpeed, dispatch } = this.props;
    if (!desiredPlaySpeed) {
      dispatch(play());
    }
    this.onVideoResume();
  }

  onVideoEnded() {
    const { dispatch, loop } = this.props;
    if (this.video) {
      dispatch(seek(loop?.startTime || 0));
      this.video.play().catch(this.onVideoError);
    }
  }

  /**
   * @param {Error} e
   */
  onHlsError(e) {
    const { dispatch } = this.props;
    dispatch(bufferVideo(true));

    if (e.type === 'mediaError' && (e.details === 'bufferStalledError' || e.details === 'bufferNudgeOnStall')) {
      // buffer but no error
      return;
    }

    if (e.type === 'networkError' && (e.response?.code === 404)) {
      this.setState({ videoError: 'This video segment has not uploaded yet or has been deleted.' });
    } else {
      this.setState({ videoError: 'Unable to load video' });
    }
  }

  /**
   * @param {Error} e
   * @param {any} [data]
   */
  onVideoError(e, data) {
    if (!e) {
      console.warn('Unknown video error', { e, data });
      return;
    }

    if (e === 'hlsError') {
      this.onHlsError(data);
      return;
    }

    if (e.name === 'AbortError') {
      // ignore
      return;
    }

    if (e.name === 'NotAllowedError') {
      // autoplay was blocked (e.g. iOS low power mode), wait for the user to press play
      this.props.dispatch(pause());
      this.props.dispatch(bufferVideo(false));
      return;
    }

    if (e.target?.src?.startsWith(window.location.origin) && e.target.src.endsWith('undefined')) {
      // TODO: figure out why the src isn't set properly
      // Sometimes an error will be thrown because we try to play
      // src: "https://connect.comma.ai/.../undefined"
      console.warn('Video error with undefined src, ignoring', { e, data });
      return;
    }

    const { dispatch } = this.props;
    dispatch(bufferVideo(true));

    if (e.type === 'networkError') {
      console.error('Network error', { e, data });
      this.setState({ videoError: 'Unable to load video. Check network connection.' });
      return;
    }

    const videoError = e.response?.code === 404
      ? 'This video segment has not uploaded yet or has been deleted.'
      : (e.response?.text || 'Unable to load video');
    this.setState({ videoError });
  }

  onVideoResume() {
    const { videoError } = this.state;
    if (videoError) this.setState({ videoError: null });
    this.props.dispatch(bufferVideo(false));
  }

  onVideoBuffering() {
    this.props.dispatch(bufferVideo(true));
  }

  updateVideoSource(prevProps) {
    let { src } = this.state;
    const { currentRoute } = this.props;
    if (!currentRoute) {
      if (src !== '') {
        this.setState({ src: '', videoError: null });
      }
      return;
    }

    if (src === '' || !prevProps.currentRoute || prevProps.currentRoute?.fullname !== currentRoute.fullname) {
      src = api.video.getQcameraStreamUrl(currentRoute.fullname, currentRoute.share_exp, currentRoute.share_sig);
      this.setState({ src, videoError: null });
      this.releaseVideo();
    }
  }

  releaseVideo() {
    this.video = null;
    setVideoClock(null);
  }

  seekVideo(offset) {
    const time = this.currentVideoTime(offset);
    if (Math.abs(this.video.currentTime - time) > 0.25) {
      this.video.currentTime = time;
    }
  }

  // inverse of currentVideoTime
  videoOffset() {
    const { currentRoute } = this.props;
    return (this.video.currentTime * 1000) + (currentRoute.videoStartOffset || 0);
  }

  currentVideoTime(offset = currentOffset()) {
    const { currentRoute } = this.props;
    if (!currentRoute) {
      return 0;
    }

    if (currentRoute.videoStartOffset) {
      offset -= currentRoute.videoStartOffset;
    }

    offset /= 1000;

    return Math.max(0, offset);
  }

  render() {
    const { desiredPlaySpeed, isBufferingVideo, currentRoute, onAudioStatusChange, isMuted } = this.props;
    const { src, videoError } = this.state;

    const onPlayerReady = (player) => {
      if (isIos()) { // ios does not support hls.js and on other browsers hls.js does not directly play the m3u8 so audioTracks are not visible
        const videoElement = player.getInternalPlayer();
        if (videoElement && videoElement.audioTracks && videoElement.audioTracks.length > 0) {
          if (onAudioStatusChange) {
            onAudioStatusChange(true);
          }
        }
      } else { // on other platforms, inspect audio tracks before hls.js changes things
        const hlsPlayer = player.getInternalPlayer('hls');
        if (hlsPlayer) {
          hlsPlayer.on('hlsBufferCodecs', (event, data) => {
            if (onAudioStatusChange) {
              onAudioStatusChange(!!data.audio);
            }
          });
        }
      }
    };

    return (
      <div className="w-full relative max-w-[964px] m-[0_auto] aspect-[1.593]">
        <VideoOverlay loading={isBufferingVideo} error={videoError} />
        <ReactPlayer
          ref={this.videoPlayer}
          url={src}
          playsinline
          muted={isMuted}
          width="100%"
          height="100%"
          playing={Boolean(currentRoute && desiredPlaySpeed)}
          onReady={onPlayerReady}
          config={{
            hlsVersion: '1.4.8',
            hlsOptions: {
              maxBufferLength: 40,
            },
          }}
          // most browsers don't support more than 16x, firefox mutes audio above 8x
          playbackRate={Math.min((isFirefox() && !isMuted) ? 8 : 16, desiredPlaySpeed || 1)}
          progressInterval={100}
          onDuration={this.onVideoLoaded}
          onProgress={this.onVideoProgress}
          onBuffer={this.onVideoBuffering}
          onBufferEnd={this.onVideoResume}
          onPlay={this.onVideoPlay}
          onPause={this.onVideoPause}
          onEnded={this.onVideoEnded}
          onError={this.onVideoError}
        />
      </div>
    );
  }
}

const stateToProps = (state) => ({
  dongleId: state.dongleId,
  desiredPlaySpeed: state.desiredPlaySpeed,
  offset: state.offset,
  startTime: state.startTime,
  isBufferingVideo: state.isBufferingVideo,
  loop: state.loop,
  routes: state.routes,
  currentRoute: state.currentRoute,
});

export default connect(stateToProps)(DriveVideo);

// src/lib/components/drive/DriveVideo.svelte
<script>
  import { untrack } from 'svelte';

  import { video as Video } from '$lib/api';
  import ErrorOutline from '$lib/icons/ErrorOutline.svelte';
  import { playback } from '$lib/state/playback.svelte.js';
  import { isFirefox, isIos } from '$lib/utils/browser';

  let { route = null, isMuted = false, onaudiostatuschange = undefined } = $props();

  // react-player never bundled hls.js: it fetched the pinned build from jsdelivr at
  // runtime and read the library off window.Hls. config.hlsVersion was '1.4.8'.
  const HLS_SDK_URL = 'https://cdn.jsdelivr.net/npm/hls.js@1.4.8/dist/hls.min.js';
  const HLS_OPTIONS = { maxBufferLength: 40 };

  // ReactPlayer held a seek made before the manifest was parsed for this long.
  const SEEK_ON_PLAY_EXPIRY = 5000;

  let videoEl = $state(null);
  let videoError = $state(null);

  let hls = null;
  let sdkRequest = null;
  // ReactPlayer's Player refused to report a duration or a current time until the
  // manifest was parsed, which is what kept syncVideo off an unloaded player.
  let isReady = false;
  let isPlaying = false;
  let startOnPlay = true;
  let seekOnPlay = null;
  let firstSeek = true;
  let wasPlaying = null;
  let lastPlaySpeed = null;

  const src = $derived(route
    ? Video.getQcameraStreamUrl(route.fullname, route.share_exp, route.share_sig)
    : '');
  // iOS plays the m3u8 natively; hls.js does not run there.
  const useHls = $derived(Boolean(src) && !isIos());
  const playing = $derived(Boolean(route && playback.desiredPlaySpeed));

  // Leading-edge debounce: run immediately, then ignore calls until `wait` ms after the last one.
  function debounceLeading(func, wait) {
    let timeout = null;
    let timestamp;

    function later() {
      const last = Date.now() - timestamp;
      if (last < wait && last >= 0) {
        timeout = setTimeout(later, wait - last);
      } else {
        timeout = null;
      }
    }

    return function debounced(...args) {
      timestamp = Date.now();
      const callNow = !timeout;
      if (!timeout) {
        timeout = setTimeout(later, wait);
      }
      if (callNow) {
        return func(...args);
      }
      return undefined;
    };
  }

  function loadHlsSdk() {
    if (window.Hls) {
      return Promise.resolve(window.Hls);
    }
    if (!sdkRequest) {
      sdkRequest = new Promise((resolve, reject) => {
        const script = document.createElement('script');
        script.src = HLS_SDK_URL;
        script.async = true;
        script.onload = () => resolve(window.Hls);
        script.onerror = (err) => {
          sdkRequest = null;
          script.remove();
          reject(err);
        };
        document.head.appendChild(script);
      });
    }
    return sdkRequest;
  }

  function getDuration() {
    if (!isReady || !videoEl) {
      return null;
    }
    const { duration, seekable } = videoEl;
    if (duration === Infinity && seekable.length > 0) {
      return seekable.end(seekable.length - 1);
    }
    return duration;
  }

  function getCurrentTime() {
    if (!isReady || !videoEl) {
      return null;
    }
    return videoEl.currentTime;
  }

  function getVideoState() {
    const currentTime = getCurrentTime();
    const { buffered } = videoEl;

    let bufferRemaining = -1;
    for (let i = 0; i < buffered.length; i += 1) {
      const end = buffered.end(i);
      if (currentTime >= buffered.start(i) && currentTime <= end) {
        bufferRemaining = end - currentTime;
        break;
      }
    }

    return {
      bufferRemaining,
      hasLoaded: bufferRemaining > 0,
    };
  }

  function currentVideoTime(offset = playback.currentOffset()) {
    if (!route) {
      return 0;
    }

    if (route.videoStartOffset) {
      offset -= route.videoStartOffset;
    }

    offset /= 1000;

    return Math.max(0, offset);
  }

  /**
   * @param {any} e hls.js error data
   */
  function onHlsError(e) {
    playback.bufferVideo(true);

    if (e.type === 'mediaError' && (e.details === 'bufferStalledError' || e.details === 'bufferNudgeOnStall')) {
      // buffer but no error
      return;
    }

    if (e.type === 'networkError' && (e.response?.code === 404)) {
      videoError = 'This video segment has not uploaded yet or has been deleted.';
    } else {
      videoError = 'Unable to load video';
    }
  }

  /**
   * @param {Error|Event|string} e
   * @param {any} [data]
   */
  function onVideoError(e, data) {
    if (!e) {
      console.warn('Unknown video error', { e, data });
      return;
    }

    if (e === 'hlsError') {
      onHlsError(data);
      return;
    }

    if (e.name === 'AbortError') {
      // ignore
      return;
    }

    if (e.target?.src?.startsWith(window.location.origin) && e.target.src.endsWith('undefined')) {
      // TODO: figure out why the src isn't set properly
      // Sometimes an error will be thrown because we try to play
      // src: "https://connect.comma.ai/.../undefined"
      console.warn('Video error with undefined src, ignoring', { e, data });
      return;
    }

    playback.bufferVideo(true);

    if (e.type === 'networkError') {
      console.error('Network error', { e, data });
      videoError = 'Unable to load video. Check network connection.';
      return;
    }

    videoError = e.response?.code === 404
      ? 'This video segment has not uploaded yet or has been deleted.'
      : (e.response?.text || 'Unable to load video');
  }

  function onVideoResume() {
    if (videoError) {
      videoError = null;
    }
  }

  function setPlaybackRate(rate) {
    try {
      videoEl.playbackRate = rate;
    } catch (err) {
      onVideoError(err);
    }
  }

  function play() {
    const playRes = videoEl.play();
    if (playRes) {
      playRes.catch(onVideoError);
    }
  }

  function seekTo(seconds) {
    if (!isReady) {
      // the player is not loaded yet, replay the seek once it starts
      if (seconds !== 0) {
        seekOnPlay = seconds;
        setTimeout(() => {
          seekOnPlay = null;
        }, SEEK_ON_PLAY_EXPIRY);
      }
      return;
    }
    videoEl.currentTime = seconds;
  }

  function onPlayerReady() {
    if (isIos()) { // ios does not support hls.js and on other browsers hls.js does not directly play the m3u8 so audioTracks are not visible
      if (videoEl?.audioTracks?.length > 0) {
        onaudiostatuschange?.(true);
      }
    } else if (hls) { // on other platforms, inspect audio tracks before hls.js changes things
      hls.on('hlsBufferCodecs', (event, data) => {
        onaudiostatuschange?.(!!data.audio);
      });
    }
  }

  // MANIFEST_PARSED for hls.js, canplay for the native branch.
  function handleReady() {
    isReady = true;
    onPlayerReady();
    if (playing) {
      play();
    }
  }

  function handlePlay() {
    isPlaying = true;
    if (startOnPlay) {
      const rate = playback.desiredPlaySpeed;
      if (rate !== 1) {
        setPlaybackRate(rate);
      }
      startOnPlay = false;
    }
    onVideoResume();
    if (seekOnPlay) {
      seekTo(seekOnPlay);
      seekOnPlay = null;
    }
  }

  function handlePause() {
    isPlaying = false;
  }

  function onVideoBuffering() {
    if (!videoEl || !route || !getDuration()) {
      playback.bufferVideo(true);
    }

    if (firstSeek) {
      firstSeek = false;
      seekTo(currentVideoTime());
    }

    const { hasLoaded } = getVideoState();
    if (!hasLoaded || videoEl.readyState < 2) {
      playback.bufferVideo(true);
    }
  }

  function syncVideoNow() {
    if (!videoEl || !getDuration()) {
      return;
    }

    let newPlaybackRate = playback.desiredPlaySpeed;
    const desiredVideoTime = currentVideoTime();
    const curVideoTime = getCurrentTime();
    const timeDiff = desiredVideoTime - curVideoTime;

    if (Math.abs(timeDiff) <= Math.max(0.1, 0.5 * newPlaybackRate)) { // newPlaybackRate = 0 when paused, set minimum 0.1 to prevent seeking when paused
      if (!isIos()) {
        newPlaybackRate = Math.max(0, newPlaybackRate + Math.round(timeDiff * 10) / 10);
      }
    } else if (desiredVideoTime === 0 && timeDiff < 0 && curVideoTime !== getDuration()) {
      // logs start earlier than video, so skip to video ts 0
      playback.seek(playback.currentOffset() - (timeDiff * 1000));
    } else {
      seekTo(desiredVideoTime);
    }
    // most browsers don't support more than 16x playback rate, firefox mutes audio above 8x causing audio to cut in and out with timeDiff rate shifts
    newPlaybackRate = Math.max(0, Math.min((isFirefox() && !isMuted) ? 8 : 16, newPlaybackRate));

    const { hasLoaded } = getVideoState();
    if (playback.isBufferingVideo && videoEl.readyState >= 4) {
      playback.bufferVideo(false);
    } else if (playback.isBufferingVideo || !hasLoaded || videoEl.readyState < 2) {
      if (!playback.isBufferingVideo) {
        playback.bufferVideo(true);
      }
      newPlaybackRate = 0; // in some circumstances, iOS won't update readyState unless temporarily paused
    }

    if (hls) {
      if (!videoEl.paused && newPlaybackRate === 0) {
        videoEl.pause();
      } else if (videoEl.playbackRate !== newPlaybackRate && newPlaybackRate !== 0) {
        videoEl.playbackRate = newPlaybackRate;
      }
      if (videoEl.paused && newPlaybackRate !== 0) {
        const playRes = videoEl.play();
        if (playRes) {
          playRes.catch(() => console.debug('[DriveVideo] play interrupted by pause'));
        }
      }
    } else {
      // TODO: fix iOS bug where video doesn't stop buffering while paused
      videoEl.playbackRate = newPlaybackRate;
    }
  }

  const syncVideo = debounceLeading(syncVideoNow, 200);

  function destroyHls() {
    if (hls) {
      hls.destroy();
      hls = null;
    }
  }

  function loadSource(el, url) {
    videoError = null;
    // Player.componentDidUpdate re-armed the one-shot playback-rate set per url
    startOnPlay = true;

    if (!useHls) {
      // FilePlayer set the src attribute and loaded the element itself
      el.load();
      return;
    }

    loadHlsSdk().then((Hls) => {
      if (videoEl !== el || src !== url) {
        return;
      }
      hls = new Hls(HLS_OPTIONS);
      hls.on(Hls.Events.MANIFEST_PARSED, handleReady);
      hls.on(Hls.Events.ERROR, (event, data) => onVideoError('hlsError', data));
      hls.loadSource(url);
      hls.attachMedia(el);
    }).catch((err) => {
      console.error('[DriveVideo] could not load hls.js', err);
    });
  }

  // componentDidUpdate re-ran syncVideo after every store change; this is read
  // only to subscribe to the fields it looks at.
  const syncKey = $derived([
    route?.fullname,
    isMuted,
    playback.offset,
    playback.startTime,
    playback.desiredPlaySpeed,
    playback.isBufferingVideo,
  ].join('|'));

  $effect(() => {
    const el = videoEl;
    const url = src;
    if (!url) {
      // updateVideoSource dropped the error along with the source
      videoError = null;
      return;
    }
    if (!el) return;

    untrack(() => loadSource(el, url));
    return () => destroyHls();
  });

  // Player.componentDidUpdate drove play/pause off the `playing` prop; the first
  // run is the mount, where the autoplay attribute and handleReady cover it.
  $effect(() => {
    const want = playing;
    untrack(() => {
      if (!videoEl) { wasPlaying = null; return; }
      const prev = wasPlaying;
      wasPlaying = want;
      if (prev === null) return;
      if (!prev && want && !isPlaying) {
        play();
      } else if (prev && !want && isPlaying) {
        videoEl.pause();
      }
    });
  });

  // ...and the playbackRate prop the same way.
  $effect(() => {
    const rate = playback.desiredPlaySpeed;
    untrack(() => {
      const prev = lastPlaySpeed;
      lastPlaySpeed = rate;
      if (prev === null || prev === rate || !videoEl) return;
      setPlaybackRate(rate);
    });
  });

  $effect(() => {
    untrack(syncVideo);
    const intv = setInterval(syncVideo, 500);
    return () => clearInterval(intv);
  });

  $effect(() => {
    if (syncKey.length) {
      untrack(syncVideo);
    }
  });
</script>

<div class="min-h-[200px] relative max-w-[964px] m-[0_auto] aspect-[1.593]">
  {#if videoError || playback.isBufferingVideo}
    <div class="z-50 absolute h-full w-full bg-page/67">
      <div class="relative text-center top-[calc(50%_-_25px)]">
        {#if videoError}
          <ErrorOutline class="mb-2 inline-block shrink-0 select-none" />
          <!-- Typography body1 -->
          <p style="display: block; margin: 0; font-size: 0.875rem; font-weight: 400; line-height: 1.46429em; color: var(--c-ink)">
            {videoError}
          </p>
        {:else}
          <!-- MuiCircularProgress, indeterminate, size={50} thickness={4} -->
          <div class="circularProgress" role="progressbar" style="width: 50px; height: 50px; color: var(--c-ink)">
            <svg viewBox="22 22 44 44">
              <circle class="circle" cx="44" cy="44" r="20" fill="none" stroke-width="4" />
            </svg>
          </div>
        {/if}
      </div>
    </div>
  {/if}
  <!-- ReactPlayer's wrapper, width/height 100%; it rendered no player without a url -->
  <div style="width: 100%; height: 100%">
    {#if src}
      <!-- svelte-ignore a11y_media_has_caption -->
      <video
        bind:this={videoEl}
        src={useHls ? undefined : src}
        muted={isMuted}
        style="width: 100%; height: 100%"
        preload="auto"
        autoplay={playing || undefined}
        playsinline
        webkit-playsinline=""
        x5-playsinline=""
        oncanplay={useHls ? undefined : handleReady}
        onwaiting={onVideoBuffering}
        onplaying={onVideoResume}
        onplay={handlePlay}
        onpause={handlePause}
        onerror={onVideoError}
      ></video>
    {/if}
  </div>
</div>

<style>
  /* MuiCircularProgress root + indeterminate */
  .circularProgress {
    display: inline-block;
    line-height: 1;
    animation: mui-progress-circular-rotate 1.4s linear infinite;
  }

  /* MuiCircularProgress circle + circleIndeterminate */
  .circle {
    stroke: currentColor;
    stroke-dasharray: 80px, 200px;
    stroke-dashoffset: 0px;
    animation: mui-progress-circular-dash 1.4s ease-in-out infinite;
  }

  @keyframes mui-progress-circular-rotate {
    100% {
      transform: rotate(360deg);
    }
  }

  @keyframes mui-progress-circular-dash {
    0% {
      stroke-dasharray: 1px, 200px;
      stroke-dashoffset: 0px;
    }
    50% {
      stroke-dasharray: 100px, 200px;
      stroke-dashoffset: -15px;
    }
    100% {
      stroke-dasharray: 100px, 200px;
      stroke-dashoffset: -120px;
    }
  }
</style>
