// src/lib/components/DriveList.svelte
<script>
  import * as Sentry from '@sentry/browser';

  import { devices as Devices } from '$lib/api';
  import { watchVisibility } from '$lib/actions/visibility';
  import { isMetric, KM_PER_MI } from '$lib/utils/conversions';
  import DriveListEmpty from './DriveListEmpty.svelte';
  import DriveListItem from './DriveListItem.svelte';
  import ScrollIntoView from './ScrollIntoView.svelte';

  let { dongleId, device, routes, lastRoutes, onfilter, onrefresh, onloadmore } = $props();

  let deviceStats = $state({});

  async function loadStats(id) {
    deviceStats = { fetching: true };
    try {
      deviceStats = { result: await Devices.fetchDeviceStats(id) };
    } catch (err) {
      console.error(err);
      Sentry.captureException(err, { fingerprint: 'drive_list_device_stats' });
      deviceStats = { error: err.message };
    }
  }

  function refreshStats() {
    if (!dongleId || device?.shared) return;
    loadStats(dongleId);
  }

  $effect(() => {
    const id = dongleId;
    const shared = device?.shared;
    deviceStats = {};
    if (id && !shared) loadStats(id);
  });

  $effect(() => watchVisibility({
    minInterval: 60,
    onVisible: () => {
      onrefresh?.();
      refreshStats();
    },
  }));

  const metric = isMetric();
  const distance = $derived(deviceStats.result
    ? Math.round(deviceStats.result.all.distance * (metric ? KM_PER_MI : 1))
    : 0);

  // Routes are cleared while fetching, so fall back to the previous set rather
  // than blanking the list.
  const displayRoutes = $derived.by(() => {
    const list = routes ?? lastRoutes;
    if (!list?.length) return [];
    // Sort with the latest drive first, working around an upstream sorting
    // issue: https://github.com/commaai/connect/issues/451
    return [...list].sort((a, b) => b.start_time_utc_millis - a.start_time_utc_millis);
  });
</script>

<div class="flex flex-col grow py-2">
  <div class="flex flex-row justify-between mx-4 pb-2 gap-2 flex-wrap">
    {#if deviceStats.result}
      <div class="flex gap-2.5 md:gap-8 items-center px-1 justify-center xss:justify-start">
        <div class="flex flex-row items-center gap-1">
          <p class="text-[0.875rem] font-semibold text-white">{distance}</p>
          <p class="text-[0.875rem]">{metric ? 'kilometers' : 'miles'}</p>
        </div>
        <div class="flex flex-row items-center gap-1">
          <p class="text-[0.875rem] font-semibold text-white">{deviceStats.result.all.routes}</p>
          <p class="text-[0.875rem]">drives</p>
        </div>
        <div class="flex flex-row items-center gap-1">
          <p class="text-[0.875rem] font-semibold text-white">{Math.round(deviceStats.result.all.minutes / 60.0)}</p>
          <p class="text-[0.875rem]">hours</p>
        </div>
      </div>
    {:else}
      <div></div>
    {/if}

    <button
      type="button"
      class="w-full xxs:w-fit flex flex-row items-center justify-center text-white normal-case py-1 px-2 rounded-md whitespace-nowrap active:scale-[0.98] cursor-pointer"
      style="background: linear-gradient(to bottom, #30373B 0%, #1D2225 150%)"
      onclick={() => onfilter?.()}
    >
      <!-- @material-ui/icons/FilterList -->
      <svg viewBox="0 0 24 24" fill="currentColor" width="1em" height="1em" class="mr-2 text-xl" aria-hidden="true">
        <path d="M10 18h4v-2h-4v2zM3 6v2h18V6H3zm3 7h12v-2H6v2z" />
      </svg>
      <p class="text-[0.875rem]">Filter</p>
    </button>
  </div>

  {#if displayRoutes.length}
    <div class="DriveList px-4 flex-1">
      {#each displayRoutes as drive, index (drive.fullname)}
        {#if index === displayRoutes.length - 1}
          <!-- fetch the next page of routes once the last entry is reached -->
          <ScrollIntoView oninview={() => onloadmore?.()}>
            <DriveListItem {drive} />
          </ScrollIntoView>
        {:else}
          <DriveListItem {drive} />
        {/if}
      {/each}
    </div>
  {/if}

  {#if !routes || routes.length === 0}
    <DriveListEmpty {device} {routes} />
  {:else if routes.length > 5}
    <div class="p-2 text-center mb-8">
      <p class="text-[0.875rem]">There are no more routes found in selected time range.</p>
    </div>
  {/if}
</div>

// src/components/Dashboard/DriveList.jsx
import React, { useState, useEffect, useCallback } from 'react';
import { connect } from 'react-redux';
import * as Sentry from '@sentry/react';
import { withStyles, Typography } from '@material-ui/core';

import { api } from '../../api/backend';
import { checkRoutesData, checkLastRoutesData } from '../../actions';
import { openModal } from '../../actions/history';
import { isMetric, KM_PER_MI } from '../../utils/conversions';
import { FilterList } from '../../icons';
import VisibilityHandler from '../VisibilityHandler';

import DriveListEmpty from './DriveListEmpty';
import DriveListItem from './DriveListItem';
import ScrollIntoView from '../ScrollIntoView'

const styles = () => ({
  header: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 16px',
  },
  drives: {
    padding: '0px 16px',
    flex: '1',
  },
  endMessage: {
    padding: 8,
    textAlign: 'center',
    marginBottom: 32,
  },
});

const DriveList = (props) => {
  const { dispatch, classes, device, dongleId, routes, lastRoutes } = props;

  const [deviceStats, setDeviceStats] = useState({});

  const fetchDeviceInfo = useCallback(async () => {
    if (!dongleId || device?.shared) {
      return;
    }
    setDeviceStats({ fetching: true });
    try {
      const resp = await api.stats.fetchDeviceStats(dongleId);
      setDeviceStats({ result: resp });
    } catch (err) {
      console.error(err);
      Sentry.captureException(err, { fingerprint: 'drive_list_device_stats' });
      setDeviceStats({ error: err.message });
    }
  }, [dongleId, device?.shared]);

  useEffect(() => {
    setDeviceStats({});
    fetchDeviceInfo();
  }, [fetchDeviceInfo]);

  const onVisible = useCallback(() => {
    dispatch(checkRoutesData());
    fetchDeviceInfo();
  }, [dispatch, fetchDeviceInfo]);

  let contentStatus;
  let content;
  if (!routes || routes.length === 0) {
    contentStatus = <DriveListEmpty device={device} routes={routes} />;
  } else if (routes && routes.length > 5) {
    contentStatus = (
      <div className={classes.endMessage}>
        <Typography>There are no more routes found in selected time range.</Typography>
      </div>
    );
  }

  // we clean up routes during data fetching, fallback to using lastRoutes to display current data
  const displayRoutes = routes || lastRoutes;
  if (displayRoutes && displayRoutes.length){
    // sort routes by start_time_utc_millis with the latest drive first
    // Workaround upstream sorting issue for now
    // possibly from https://github.com/commaai/connect/issues/451
    displayRoutes.sort((a, b) => b.start_time_utc_millis - a.start_time_utc_millis);
    const routesSize = displayRoutes.length

    content = (
      <div className={`${classes.drives} DriveList`}>
        {displayRoutes.map((drive, index) => {
            // when the last item is in view, we fetch the next routes
            return (index === routesSize - 1 ?
              <ScrollIntoView key={drive.fullname} onInView={() => dispatch(checkLastRoutesData())}>
                <DriveListItem drive={drive} />
              </ScrollIntoView> :
              <DriveListItem key={drive.fullname} drive={drive} />)
        })}
      </div>
    );
  }

  const renderStats = () => {
    if (!deviceStats.result) {
      return <div />;
    }

    const metric = isMetric();
    const distance = metric
      ? Math.round(deviceStats.result.all.distance * KM_PER_MI)
      : Math.round(deviceStats.result.all.distance);

    return (
      <div className="flex gap-2.5 md:gap-8 items-center px-1 justify-center xss:justify-start">
        <div className="flex flex-row items-center gap-1">
          <Typography className="font-semibold text-white">
            { distance }
          </Typography>
          <Typography>
            { metric ? 'kilometers' : 'miles' }
          </Typography>
        </div>
        <div className="flex flex-row items-center gap-1">
          <Typography className="font-semibold text-white">
            { deviceStats.result.all.routes }
          </Typography>
          <Typography>drives</Typography>
        </div>
        <div className="flex flex-row items-center gap-1">
          <Typography className="font-semibold text-white">
            { Math.round(deviceStats.result.all.minutes / 60.0) }
          </Typography>
          <Typography>hours</Typography>
        </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col grow py-2">
      <VisibilityHandler onVisible={onVisible} minInterval={60} />
      <div className="flex flex-row justify-between mx-4 pb-2 gap-2 flex-wrap">
        { renderStats() }
        <button
          className="w-full xxs:w-fit flex flex-row items-center justify-center text-white normal-case py-1 px-2 rounded-md whitespace-nowrap active:scale-[0.98] cursor-pointer"
          style={{ background: 'linear-gradient(to bottom, #30373B 0%, #1D2225 150%)' }}
          onClick={() => dispatch(openModal('filter'))}
        >
          <FilterList className="mr-2 text-xl" />
          <Typography>Filter</Typography>
        </button>
      </div>
      {content}
      {contentStatus}
    </div>
  );
};

const stateToProps = (state) => ({
  dongleId: state.dongleId,
  routes: state.routes,
  lastRoutes: state.lastRoutes,
  device: state.device,
});

export default connect(stateToProps)(withStyles(styles)(DriveList));
