// src/lib/components/DriveListEmpty.svelte
<script>
  import { innerWidth } from 'svelte/reactivity/window';

  let { device, routes } = $props();

  const containerPadding = $derived((innerWidth.current ?? 1280) > 520 ? 36 : 16);
</script>

<!-- MUI <Grid container>, flex: 0 -->
<div class="box-border flex w-full flex-wrap" style="flex: 0; padding: 16px {containerPadding}px">
  {#if device && routes == null}
    <p class="text-[0.875rem]">Loading...</p>
  {:else if routes?.length === 0}
    <p class="text-[0.875rem]">No routes found in selected time range.</p>
  {/if}
</div>

// src/components/Dashboard/DriveListEmpty.jsx
import React from 'react';
import { Grid, withStyles } from '@material-ui/core';

import { useWindowWidth } from '../../hooks/window';

const styles = () => ({
  zeroState: {
    flex: '0',
  },
});

const DriveListEmpty = (props) => {
  const windowWidth = useWindowWidth();
  const { classes, device, routes } = props;
  let zeroRidesEle = null;

  if (device && routes === null) {
    zeroRidesEle = <p>Loading...</p>;
  } else if (routes?.length === 0) {
    zeroRidesEle = (
      <p>No routes found in selected time range.</p>
    );
  }

  const containerPadding = windowWidth > 520 ? 36 : 16;
  return (
    <Grid container className={classes.zeroState} style={{ padding: `16px ${containerPadding}px` }}>
      {zeroRidesEle}
    </Grid>
  );
};

export default withStyles(styles)(DriveListEmpty);
