// src/lib/components/AppHeader.svelte
<script>
  import AccountMenu from './AccountMenu.svelte';
  import AccountIcon from '$lib/icons/AccountIcon.svelte';
  import MenuIcon from '$lib/icons/MenuIcon.svelte';

  let { profile, dongleId, showDrawerButton = false, drawerIsOpen = false, ontoggledrawer } = $props();

  let menuOpen = $state(false);

  const home = $derived(dongleId ? `/${dongleId}` : '/');
</script>

<!-- MUI AppBar position="sticky" elevation={1} -->
<header
  class="sticky top-0 z-30 flex flex-row flex-wrap items-center justify-between bg-[#1D2225] p-[7.5px]
         border-b border-white/10 shadow-[0_2px_4px_-1px_rgba(0,0,0,0.2),0_4px_5px_0_rgba(0,0,0,0.14),0_1px_10px_0_rgba(0,0,0,0.12)]"
>
  <div class="flex flex-nowrap items-center">
    {#if showDrawerButton}
      <button
        type="button"
        aria-label="menu"
        class="mr-3 flex h-12 w-12 cursor-pointer items-center justify-center rounded-full text-white hover:bg-white/10"
        onclick={() => ontoggledrawer(!drawerIsOpen)}
      >
        <MenuIcon />
      </button>
    {:else}
      <a href={home} style="line-height: 0">
        <img alt="comma" src="/images/comma-white.png" class="mx-[28px] h-[34px] w-[18.9px]" />
      </a>
    {/if}
    <a href={home}>
      <p class="text-[20px] font-extrabold">connect</p>
    </a>
  </div>

  <div class="flex flex-row gap-2">
    <div class="relative">
      <button
        type="button"
        aria-label="account menu"
        aria-haspopup="true"
        aria-expanded={menuOpen}
        class="flex h-12 w-12 cursor-pointer items-center justify-center rounded-full hover:bg-white/10"
        onclick={() => { menuOpen = !menuOpen; }}
      >
        <AccountIcon class="h-[34px] w-[34px] text-white/30" />
      </button>
      {#if profile}
        <AccountMenu {profile} open={menuOpen} onclose={() => { menuOpen = false; }} />
      {/if}
    </div>
  </div>
</header>

// src/components/AppHeader/index.jsx
import React, { Suspense, useCallback, useState } from 'react';
import { connect } from 'react-redux';

import { withStyles } from '@material-ui/core/styles';
import { Typography, IconButton, AppBar } from '@material-ui/core';
import MenuIcon from '@material-ui/icons/Menu';

import MyCommaAuth from '@commaai/my-comma-auth';

import { selectDevice } from '../../actions';
import { AccountIcon } from '../../icons';
import Colors from '../../colors';
import { filterRegularClick } from '../../utils';

import AccountMenu from './AccountMenu';
import PWAIcon from '../PWAIcon';

const styles = () => ({
  header: {
    backgroundColor: '#1D2225',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 7.5,
    flexWrap: 'wrap',
  },
  titleContainer: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'nowrap',
  },
  logo: {
    alignItems: 'center',
    display: 'flex',
    maxWidth: 200,
    textDecoration: 'none',
  },
  logoImgLink: {
    lineHeight: 0,
  },
  logoImg: {
    height: 34,
    width: 18.9,
    margin: '0px 28px',
  },
  logoText: {
    fontSize: 20,
    fontWeight: 800,
  },
  accountIcon: {
    color: Colors.white30,
    height: 34,
    width: 34,
  },
});

const AppHeader = ({
  profile, classes, dispatch, drawerIsOpen, viewingRoute, showDrawerButton,
  forwardRef, handleDrawerStateChanged, primeNav, dongleId,
}) => {
  const [menuOpen, setMenuOpen] = useState(false);

  const handleClickedAccount = useCallback(() => {
    if (MyCommaAuth.isAuthenticated()) {
      setMenuOpen((prev) => !prev);
    } else if (window.location) {
      window.location = window.location.origin;
    }
  }, []);

  const handleClose = useCallback(() => {
    setMenuOpen(false);
  }, []);

  const toggleDrawer = useCallback(() => {
    handleDrawerStateChanged(!drawerIsOpen);
  }, [drawerIsOpen, handleDrawerStateChanged]);

  const open = menuOpen;

  return (
    <>
      <AppBar position="sticky" elevation={1}>
        <div ref={forwardRef} className={classes.header}>
          <div className={classes.titleContainer}>
            {showDrawerButton ? (
              <IconButton
                aria-label="menu"
                className="mr-3"
                onClick={toggleDrawer}
              >
                <MenuIcon />
              </IconButton>
            )
              : (
                <a
                  href={`/${dongleId}`}
                  className={classes.logoImgLink}
                  onClick={filterRegularClick(() => dispatch(selectDevice(dongleId)))}
                >
                  <img alt="comma" src="/images/comma-white.png" className={classes.logoImg} />
                </a>
              )}
            <a
              href={`/${dongleId}`}
              onClick={filterRegularClick(() => dispatch(selectDevice(dongleId)))}
            >
              <Typography className={classes.logoText}>connect</Typography>
            </a>
          </div>
          <div className="flex flex-row gap-2">
            <Suspense><PWAIcon /></Suspense>
            <div className="relative">
              <IconButton
                aria-expanded={open}
                aria-haspopup="true"
                onClick={handleClickedAccount}
                aria-label="account menu"
              >
                <AccountIcon className={classes.accountIcon} />
              </IconButton>
              {Boolean(MyCommaAuth.isAuthenticated() && profile) && (
                <AccountMenu
                  open={open}
                  onClose={handleClose}
                  profile={profile}
                />
              )}
            </div>
          </div>
        </div>
      </AppBar>
    </>
  );
};

const stateToProps = (state) => ({
  dongleId: state.dongleId,
  filter: state.filter,
  profile: state.profile,
  primeNav: state.primeNav,
});

export default connect(stateToProps)(withStyles(styles)(AppHeader));
