// src/components/AppDrawer/index.jsx
import React, { useCallback, useEffect, useRef } from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';

import Drawer from '@material-ui/core/Drawer';

import DeviceList from '../Dashboard/DeviceList';

import { navigate } from '../../actions/navigation';

const listener = (ev) => ev.stopPropagation();

const AppDrawer = ({
  dispatch, isPermanent, drawerIsOpen, selectedDongleId, handleDrawerStateChanged, width,
}) => {
  const contentRef = useRef(null);

  useEffect(() => {
    const el = contentRef.current;
    if (el) el.addEventListener('touchstart', listener);
    return () => {
      if (el) el.removeEventListener('touchstart', listener);
    };
  }, [contentRef]);

  const toggleDrawerOff = useCallback(() => {
    handleDrawerStateChanged(false);
  }, [handleDrawerStateChanged]);

  const handleDeviceSelected = useCallback((dongleId) => {
    dispatch(navigate({ page: 'dashboard', dongleId }));
    toggleDrawerOff();
  }, [dispatch, toggleDrawerOff]);

  return (
    <Drawer
      open={isPermanent || drawerIsOpen}
      onClose={toggleDrawerOff}
      variant={isPermanent ? 'permanent' : 'temporary'}
      PaperProps={{ style: { width, top: 'auto' } }}
    >
      <div ref={contentRef} className="flex flex-col h-full bg-[linear-gradient(180deg,#1B2023_0%,#111516_100%)] ml-safe-left">
        {!isPermanent
          && (
            <Link to="/" className="flex items-center min-h-[64px] mx-2">
              <img alt="comma" src="/images/comma-white.png" className="w-[18.9px] mx-6" />
              <span className="text-xl font-extrabold">connect</span>
            </Link>
          )}
        <DeviceList
          selectedDevice={selectedDongleId}
          handleDeviceSelected={handleDeviceSelected}
        />
      </div>
    </Drawer>
  );
};

const stateToProps = (state) => ({
  selectedDongleId: state.dongleId,
  device: state.device,
});

export default connect(stateToProps)(AppDrawer);

// src/lib/components/AppDrawer.svelte
<script>
  import DeviceList from './DeviceList.svelte';

  let {
    devices, device, profile, selectedDongleId,
    isPermanent = false, open = false, width = 280,
    onclose, onselect, onsettings,
  } = $props();

  const visible = $derived(isPermanent || open);
</script>

<!-- Temporary drawers sit above the page behind a scrim; permanent ones are
     part of the layout, which is what MUI's Drawer variants did. -->
{#if !isPermanent && open}
  <div
    class="fixed inset-0 z-40 bg-black/50"
    role="presentation"
    onclick={onclose}
    onkeydown={(e) => e.key === 'Escape' && onclose()}
  ></div>
{/if}

<aside
  class="fixed left-0 bottom-0 z-40 transition-transform"
  class:top-0={!isPermanent}
  class:top-auto={isPermanent}
  style="width: {width}px; {isPermanent ? '' : `transform: translateX(${visible ? '0' : '-100%'})`}"
  aria-hidden={!visible}
>
  <div class="ml-safe-left flex h-full flex-col bg-[linear-gradient(180deg,#1B2023_0%,#111516_100%)]">
    {#if !isPermanent}
      <a href="/" class="mx-2 flex min-h-[64px] items-center" onclick={onclose}>
        <img alt="comma" src="/images/comma-white.png" class="mx-6 w-[18.9px]" />
        <span class="text-xl font-extrabold">connect</span>
      </a>
    {/if}

    <DeviceList {devices} {device} {profile} {selectedDongleId} {onselect} {onsettings} />
  </div>
</aside>
