// src/components/utils/InfoTooltip.jsx
import { ClickAwayListener, Tooltip, Typography } from '@mui/material';
import { withStyles } from '@mui/styles';
import { useState } from 'react';

import { InfoOutline } from '../../icons';

const styles = (theme) => ({
  arrowPopper: {
    opacity: 1,
    '& $arrowArrow': {
      bottom: 0,
      left: 0,
      marginBottom: '-0.9em',
      width: '3em',
      height: '1em',
      '&::before': {
        borderWidth: '1em 1em 0 1em',
        borderColor: `${theme.palette.grey[900]} transparent transparent transparent`,
      },
    },
  },
  arrowArrow: {
    position: 'absolute',
    fontSize: 7,
    width: '3em',
    height: '3em',
    '&::before': {
      content: '""',
      margin: 'auto',
      display: 'block',
      width: 0,
      height: 0,
      borderStyle: 'solid',
    },
  },
  tooltip: {
    background: theme.palette.grey[900],
    marginBottom: 8,
  },
  icon: {
    marginLeft: theme.spacing.unit,
    fontSize: 18,
  },
});

const InfoTooltip = ({ classes, title }) => {
  const [arrowRef, setArrowRef] = useState(null);
  const [open, setOpen] = useState(false);

  const handleArrowRef = (node) => {
    setArrowRef(node);
  };

  const onTooltipOpen = () => {
    setOpen(true);
  };

  const onTooltipClose = () => {
    setOpen(false);
  };

  return (
    <ClickAwayListener onClickAway={onTooltipClose}>
      <Tooltip
        PopperProps={{
          popperOptions: {
            modifiers: {
              arrow: {
                enabled: Boolean(arrowRef),
                element: arrowRef,
              },
            },
          },
        }}
        title={
          <>
            <Typography color="inherit">{title}</Typography>
            <span className={classes.arrowArrow} ref={handleArrowRef} />
          </>
        }
        onOpen={onTooltipOpen}
        onClose={onTooltipClose}
        open={open}
        classes={{ tooltip: classes.tooltip, popper: classes.arrowPopper }}
        placement="top"
      >
        <InfoOutline className={classes.icon} onClick={onTooltipOpen} />
      </Tooltip>
    </ClickAwayListener>
  );
};

export default withStyles(styles)(InfoTooltip);

// src/lib/components/InfoTooltip.svelte
<script>
  import Tooltip from './Tooltip.svelte';

  let { title } = $props();

  let open = $state(false);

  // ClickAwayListener equivalent: any pointerdown outside dismisses the bubble.
  $effect(() => {
    if (!open) return;
    const close = () => { open = false; };
    document.addEventListener('pointerdown', close, true);
    return () => document.removeEventListener('pointerdown', close, true);
  });
</script>

{#snippet panel()}
  <!-- MUI wrapped the title in a Typography (body1); .tooltip's 10px is the bubble only -->
  <p class="text-[14px]" style="line-height: 1.46429em">{title}</p>
  <span class="arrow"></span>
{/snippet}

<Tooltip
  bind:open
  placement="top"
  offset={8}
  opacity={1}
  panelClass="rounded-[4px] bg-[var(--c-grey-900)] px-2 py-1 text-[10px] text-ink"
  {panel}
>
  <!-- @material-ui/icons InfoOutline, at theme.spacing.unit marginLeft / fontSize 18 -->
  <svg
    viewBox="0 -960 960 960"
    fill="currentColor"
    width="1em"
    height="1em"
    style="font-size:18px"
    class="ml-2 shrink-0 cursor-pointer"
    role="button"
    tabindex="0"
    aria-label={title}
    onclick={() => { open = true; }}
    onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open = true; } }}
  >
    <path d="M453-280h60v-240h-60v240Zm27-314q14 0 23-9t10-23q0-14-9-24-10-10-24-10t-23 10-10 24q0 14 9 23 10 9 24 9Zm0 514q-82 0-155-31t-128-86q-54-55-86-128-31-73-31-155 0-83 32-156 31-73 86-127t127-85q73-32 156-32 82 0 155 32 73 31 127 85t86 127q31 73 31 156 0 82-31 155t-86 127q-54 55-127 86-73 32-156 32Zm0-60q142 0 241-99t99-241q0-142-99-241t-241-99q-141 0-240 99-100 99-100 241 0 141 100 241t241 99Zm0-340Z" />
  </svg>
</Tooltip>

<style>
  /* MUI's popper arrow modifier: a 7px-based triangle hanging off the bubble. */
  .arrow {
    position: absolute;
    bottom: 0;
    left: 50%;
    transform: translateX(-50%);
    margin-bottom: -0.9em;
    font-size: 7px;
    width: 3em;
    height: 1em;
  }

  .arrow::before {
    content: '';
    margin: auto;
    display: block;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 1em 1em 0 1em;
    border-color: var(--c-grey-900) transparent transparent transparent;
  }
</style>
