// src/components/Timeline/index.jsx
// timeline minimap
// rapidly change high level timeline stuff
// rapid seeking, etc
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { withStyles } from '@material-ui/core/styles';
import dayjs from 'dayjs';

import Thumbnails from './thumbnails';
import theme from '../../theme';
import { navigateToDrive } from '../../actions';
import Colors from '../../colors';
import { currentOffset } from '../../timeline';
import { seek } from '../../timeline/playback';
import { getSegmentNumber } from '../../utils';

const styles = () => ({
  base: {
    position: 'relative',
  },
  segments: {
    position: 'relative',
    left: '0px',
    width: '100%',
    overflow: 'hidden',
    height: 12,
  },
  segment: {
    position: 'absolute',
    height: 12,
    background: theme.palette.states.drivingBlue,
  },
  statusGradient: {
    background: 'linear-gradient(rgba(0, 0, 0, 0.0) 4%, rgba(255, 255, 255, 0.025) 10%, rgba(0, 0, 0, 0.1) 25%, rgba(0, 0, 0, 0.4))',
    height: 12,
    left: 0,
    pointerEvents: 'none',
    position: 'absolute',
    top: 0,
    width: '100%',
    zIndex: 2,
  },
  segmentColor: {
    position: 'absolute',
    display: 'inline-block',
    height: 12,
    width: '100%',
    '&.active': {},
    '&.engage': {
      background: theme.palette.states.engagedGreen,
    },
    '&.overriding': {
      background: theme.palette.states.engagedGrey,
    },
    '&.alert': {
      '&.userPrompt': {
        background: theme.palette.states.alertOrange,
      },
      '&.critical': {
        background: theme.palette.states.alertRed,
      },
    },
    '&.bookmark, &.flag': {  // TODO: remove flag selector once 14 days expires old events caches
      background: theme.palette.states.userBookmark,
      zIndex: 1,
    },
  },
  thumbnails: {
    height: 20,
    width: '100%',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    userSelect: 'none',
    '& > div': {
      display: 'inline-block',
    },
  },
  ruler: {
    backgroundColor: 'rgb(37, 51, 61)',
    touchAction: 'none',
    width: '100%',
    height: 44,
  },
  rulerRemaining: {
    backgroundColor: 'rgba(29, 34, 37, 0.9)',
    borderLeft: '1px solid #D8DDDF',
    position: 'absolute',
    left: 0,
    height: 44,
    opacity: 0.45,
    pointerEvents: 'none',
    width: '100%',
  },
  loopStart: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderRight: '1px solid rgba(0, 0, 0, 0.8)',
    position: 'absolute',
    left: 0,
    height: 44,
    pointerEvents: 'none',
  },
  loopEnd: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    borderLeft: '1px solid rgba(0, 0, 0, 0.8)',
    position: 'absolute',
    right: 0,
    height: 44,
    pointerEvents: 'none',
  },
  dragHighlight: {
    pointerEvents: 'none',
    background: 'rgba(255, 255, 255, 0.1)',
    borderLeft: '1px solid rgba(255, 255, 255, 0.3)',
    borderRight: '1px solid rgba(255, 255, 255, 0.3)',
    position: 'absolute',
    height: 44,
  },
  hoverBead: {
    zIndex: 3,
    textAlign: 'center',
    borderRadius: 14,
    fontSize: '0.7em',
    padding: '3px 4px',
    border: `1px solid ${Colors.white10}`,
    backgroundColor: Colors.grey800,
    color: Colors.white,
    position: 'absolute',
    top: 83,
    left: 0,
    width: 80,
  },
});

const AlertStatusCodes = [
  'normal',
  'userPrompt',
  'critical',
];

function percentFromPointerEvent(ev) {
  const boundingBox = ev.currentTarget.getBoundingClientRect();
  const x = ev.pageX - boundingBox.left;
  return x / boundingBox.width;
}

class Timeline extends Component {
  constructor(props) {
    super(props);

    this.getOffset = this.getOffset.bind(this);
    this.handleClick = this.handleClick.bind(this);
    this.handlePointerMove = this.handlePointerMove.bind(this);
    this.handlePointerDown = this.handlePointerDown.bind(this);
    this.handlePointerUp = this.handlePointerUp.bind(this);
    this.handlePointerLeave = this.handlePointerLeave.bind(this);
    this.percentToOffset = this.percentToOffset.bind(this);
    this.segmentNum = this.segmentNum.bind(this);
    this.onRulerRef = this.onRulerRef.bind(this);
    this.renderRoute = this.renderRoute.bind(this);

    this.rulerRemaining = React.createRef();
    this.rulerRef = React.createRef();
    this.dragBar = React.createRef();
    this.hoverBead = React.createRef();
    this.thumbnailsRef = React.createRef();

    const { zoomOverride, zoom } = this.props;
    this.state = {
      dragging: null,
      hoverX: null,
      zoom: zoomOverride || zoom,
      thumbnail: {
        height: 0,
        width: 0,
      },
    };
  }

  componentDidMount() {
    this.mounted = true;
    requestAnimationFrame(this.getOffset);
    this.componentDidUpdate({});

    if (typeof ResizeObserver !== 'undefined' && this.thumbnailsRef.current) {
      this.resizeObserver = new ResizeObserver((entries) => {
        const entry = entries[0];
        if (!entry) {
          return;
        }
        const { width, height } = entry.contentRect;
        this.setState({ thumbnail: { width, height } });
      });
      this.resizeObserver.observe(this.thumbnailsRef.current);
    }
  }

  componentDidUpdate(prevProps) {
    const { zoomOverride, zoom } = this.props;
    if (prevProps.zoomOverride !== zoomOverride || prevProps.zoom !== zoom) {
      this.setState({ zoom: zoomOverride || zoom });
    }
  }

  componentWillUnmount() {
    this.mounted = false;
    if (this.resizeObserver) {
      this.resizeObserver.disconnect();
      this.resizeObserver = null;
    }
  }

  handleClick(ev) {
    const { dragging } = this.state;
    if (!dragging || Math.abs(dragging[1] - dragging[0]) <= 3) {
      const percent = percentFromPointerEvent(ev);
      this.props.dispatch(seek(this.percentToOffset(percent)));
    }
  }

  handlePointerDown(ev) {
    if (ev.button !== 0) {
      return;
    }

    ev.preventDefault();
    document.addEventListener('pointerup', this.handlePointerUp);
    document.addEventListener('pointermove', this.handlePointerMove);
    this.setState({ dragging: [ev.pageX, ev.pageX] });
  }

  handlePointerMove(ev) {
    ev.preventDefault();
    const { dragging } = this.state;
    if (!this.rulerRef.current) {
      return;
    }
    ev.preventDefault();

    const rulerBounds = this.rulerRef.current.getBoundingClientRect();
    const endDrag = Math.max(rulerBounds.x, Math.min(rulerBounds.x + rulerBounds.width, ev.pageX));
    if (dragging) {
      this.setState({ dragging: [dragging[0], endDrag] });
    }
    this.setState({ hoverX: endDrag });
  }

  handlePointerUp(ev) {
    const { route } = this.props;

    // prevent preventDefault for back(3) and forward(4) mouse buttons
    if (ev.button !== 3 && ev.button !== 4) {
      ev.preventDefault();
    }

    document.removeEventListener('pointerup', this.handlePointerUp);
    document.removeEventListener('pointermove', this.handlePointerMove);
    const { dragging } = this.state;
    if (!dragging) {
      return;
    }
    this.setState({ dragging: null });

    const rulerBounds = this.rulerRef.current.getBoundingClientRect();
    const startPercent = (Math.min(dragging[0], dragging[1]) - rulerBounds.x) / rulerBounds.width;
    const endPercent = (Math.max(dragging[0], dragging[1]) - rulerBounds.x) / rulerBounds.width;
    const startOffset = Math.round(this.percentToOffset(startPercent));
    const endOffset = Math.round(this.percentToOffset(endPercent));

    if (Math.abs(dragging[1] - dragging[0]) > 3) {
      const offset = currentOffset();
      if (offset < startOffset || offset > endOffset) {
        this.props.dispatch(seek(startOffset));
      }
      this.props.dispatch(navigateToDrive(route, startOffset, endOffset));
    } else if (ev.currentTarget !== document) {
      this.handleClick(ev);
    }
  }

  handlePointerLeave() {
    this.setState({ hoverX: null });
  }

  onRulerRef(el) {
    this.rulerRef.current = el;
    if (el) {
      el.addEventListener('touchstart', (ev) => ev.stopPropagation());
    }
  }

  getOffset() {
    if (!this.mounted) {
      return;
    }
    requestAnimationFrame(this.getOffset);
    let offset = currentOffset();
    if (this.seekIndex) {
      offset = this.seekIndex;
    }
    offset = Math.floor(offset);
    const percent = this.offsetToPercent(offset);
    if (this.rulerRemaining.current && this.rulerRemaining.current.parentElement) {
      this.rulerRemaining.current.style.left = `${Math.floor(10000 * percent) / 100}%`;
      this.rulerRemaining.current.style.width = `${100 - Math.floor(10000 * percent) / 100}%`;
    }
  }

  percentToOffset(perc) {
    const { zoom } = this.state;
    return perc * (zoom.end - zoom.start) + zoom.start;
  }

  offsetToPercent(offset) {
    const { zoom } = this.state;
    return (offset - zoom.start) / (zoom.end - zoom.start);
  }

  segmentNum(offset) {
    const { route } = this.props;
    if (route) {
      return getSegmentNumber(route, offset);
    }
    return null;
  }

  renderRoute() {
    const { classes, route } = this.props;
    const { zoom } = this.state;

    if (!route.events) {
      return null;
    }

    const zoomDuration = zoom.end - zoom.start;
    const startPerc = (100 * (-zoom.start)) / zoomDuration;
    const widthPerc = (100 * route.duration) / zoomDuration;

    const style = {
      width: `${widthPerc}%`,
      left: `${startPerc}%`,
    };
    return (
      <div key={route.fullname} className={classes.segment} style={style}>
        { this.renderRouteEvents(route) }
      </div>
    );
  }

  renderRouteEvents(route) {
    const { classes } = this.props;
    if (!route.events) {
      return null;
    }

    return route.events
      .filter((event) => event.data && event.data.end_route_offset_millis)
      .map((event) => {
        const style = {
          left: `${(event.route_offset_millis / route.duration) * 100}%`,
          width: `${((event.data.end_route_offset_millis - event.route_offset_millis) / route.duration) * 100}%`,
          minWidth: '1px',
        };
        const statusCls = event.data.alertStatus ? `${AlertStatusCodes[event.data.alertStatus]}` : '';
        return (
          <div
            key={route.fullname + event.route_offset_millis + event.type}
            style={style}
            className={ `${classes.segmentColor} ${event.type} ${statusCls}` }
          />
        );
      });
  }

  render() {
    const { classes, hasRuler, className, route, thumbnailsVisible } = this.props;
    const { thumbnail, hoverX, dragging } = this.state;

    const hasRulerCls = hasRuler ? 'hasRuler' : '';

    let rulerBounds;
    if (this.rulerRef.current) {
      rulerBounds = this.rulerRef.current.getBoundingClientRect();
    }

    let hoverString; let
      hoverStyle;
    if (rulerBounds && hoverX) {
      const hoverOffset = this.percentToOffset((hoverX - rulerBounds.x) / rulerBounds.width);
      hoverStyle = { left: Math.max(-10, Math.min(rulerBounds.width - 70, hoverX - rulerBounds.x - 40)) };
      if (!Number.isNaN(hoverOffset)) {
        hoverString = dayjs(route.start_time_utc_millis + hoverOffset).format('HH:mm:ss');
        const segNum = this.segmentNum(hoverOffset);
        if (segNum !== null) {
          hoverString = `${segNum}, ${hoverString}`;
        }
      }
    }

    let draggerStyle;
    if (rulerBounds && dragging && Math.abs(dragging[1] - dragging[0]) > 0) {
      draggerStyle = {
        left: `${Math.min(dragging[1], dragging[0]) - rulerBounds.x}px`,
        width: `${Math.abs(dragging[1] - dragging[0])}px`,
      };
    }

    const baseWidthStyle = { width: '100%' };

    return (
      <div className={className}>
        <div role="presentation" className={ `${classes.base} ${hasRulerCls}` } style={ baseWidthStyle }>
          <div className={ `${classes.segments} ${hasRulerCls}` }>
            { route && this.renderRoute() }
            <div className={ `${classes.statusGradient} ${hasRulerCls}` } />
          </div>
          <div ref={this.thumbnailsRef} className={`${classes.thumbnails} ${hasRulerCls}`}>
            {thumbnailsVisible && (
              <Thumbnails
                className={classes.thumbnail}
                currentRoute={route}
                percentToOffset={this.percentToOffset}
                thumbnail={thumbnail}
                hasRuler={hasRuler}
              />
            )}
          </div>
          { hasRuler && (
            <>
              <div
                aria-label="Drive timeline"
                role="slider"
                tabIndex={0}
                ref={ this.onRulerRef }
                className={classes.ruler}
                onPointerDown={this.handlePointerDown}
                onPointerUp={this.handlePointerUp}
                onPointerMove={this.handlePointerMove}
                onPointerLeave={this.handlePointerLeave}
              >
                <div ref={this.rulerRemaining} className={classes.rulerRemaining} />
                { draggerStyle && <div ref={this.dragBar} className={classes.dragHighlight} style={draggerStyle} /> }
              </div>
              { hoverString && (
                <div ref={this.hoverBead} className={classes.hoverBead} style={hoverStyle}>
                  { hoverString }
                </div>
              ) }
            </>
          ) }
        </div>
      </div>
    );
  }
}

const stateToProps = (state) => ({
  zoom: state.zoom,
  loop: state.loop,
});

export default connect(stateToProps)(withStyles(styles)(Timeline));

// src/lib/components/Timeline.svelte
<script>
  import dayjs from 'dayjs';

  import Thumbnails from './Thumbnails.svelte';
  import { playback } from '$lib/state/playback.svelte.js';
  import { getRouteEvents } from '$lib/state/routes.svelte.js';
  import { getSegmentNumber } from '$lib/utils';
  import { keepTouch } from '$lib/attachments/keep-touch';

  let {
    route,
    thumbnailsVisible = false,
    zoomOverride = null,
    hasRuler = false,
    class: className = undefined,
    onrange = undefined,
  } = $props();

  // theme.palette.states.*
  const DRIVING_BLUE = '#175886';
  const ENGAGED_GREEN = '#178645';
  const ENGAGED_GREY = '#919b95';
  const ALERT_ORANGE = '#da6f25';
  const ALERT_RED = '#c92231';
  const USER_BOOKMARK = '#e3d756';

  const AlertStatusCodes = ['normal', 'userPrompt', 'critical'];

  const STATUS_GRADIENT = 'linear-gradient(rgba(0, 0, 0, 0.0) 4%, rgba(255, 255, 255, 0.025) 10%,'
    + ' rgba(0, 0, 0, 0.1) 25%, rgba(0, 0, 0, 0.4))';

  let dragging = $state(null);
  let hoverX = $state(null);
  let rulerBounds = $state(null);
  let thumbnail = $state({ width: 0, height: 0 });

  let thumbnailsEl = $state(null);
  let rulerEl = $state(null);
  let rulerRemainingEl = $state(null);

  const zoom = $derived(zoomOverride || playback.zoom);
  const hasRulerCls = $derived(hasRuler ? 'hasRuler' : '');

  const events = $derived(route ? getRouteEvents(route.fullname) : null);

  const routeStyle = $derived.by(() => {
    if (!route || !zoom) {
      return null;
    }
    const zoomDuration = zoom.end - zoom.start;
    return `width: ${(100 * route.duration) / zoomDuration}%; left: ${(100 * -zoom.start) / zoomDuration}%`;
  });

  const bands = $derived.by(() => {
    if (!route || !events) {
      return [];
    }
    return events
      .filter((event) => event.data && event.data.end_route_offset_millis)
      .map((event) => {
        const left = (event.route_offset_millis / route.duration) * 100;
        const width = ((event.data.end_route_offset_millis - event.route_offset_millis) / route.duration) * 100;
        let style = `left: ${left}%; width: ${width}%; min-width: 1px`;
        const background = bandBackground(event);
        if (background) {
          style += `; background: ${background}`;
        }
        // TODO: remove flag once 14 days expires old events caches
        if (event.type === 'bookmark' || event.type === 'flag') {
          style += '; z-index: 1';
        }
        return style;
      });
  });

  function bandBackground(event) {
    switch (event.type) {
      case 'engage':
        return ENGAGED_GREEN;
      case 'overriding':
        return ENGAGED_GREY;
      case 'bookmark':
      case 'flag':
        return USER_BOOKMARK;
      case 'alert': {
        const status = event.data.alertStatus ? AlertStatusCodes[event.data.alertStatus] : '';
        if (status === 'userPrompt') return ALERT_ORANGE;
        if (status === 'critical') return ALERT_RED;
        return null;
      }
      default:
        return null;
    }
  }

  function percentToOffset(perc) {
    return perc * (zoom.end - zoom.start) + zoom.start;
  }

  function offsetToPercent(offset) {
    return (offset - zoom.start) / (zoom.end - zoom.start);
  }

  function percentFromPointerEvent(ev) {
    const boundingBox = ev.currentTarget.getBoundingClientRect();
    return (ev.pageX - boundingBox.left) / boundingBox.width;
  }

  const hover = $derived.by(() => {
    if (!route || !zoom || !rulerBounds || !hoverX) {
      return null;
    }
    const hoverOffset = percentToOffset((hoverX - rulerBounds.x) / rulerBounds.width);
    if (Number.isNaN(hoverOffset)) {
      return null;
    }
    let text = dayjs(route.start_time_utc_millis + hoverOffset).format('HH:mm:ss');
    const segNum = getSegmentNumber(route, hoverOffset);
    if (segNum !== null) {
      text = `${segNum}, ${text}`;
    }
    return {
      text,
      left: Math.max(-10, Math.min(rulerBounds.width - 70, hoverX - rulerBounds.x - 40)),
    };
  });

  const draggerStyle = $derived.by(() => {
    if (!rulerBounds || !dragging || Math.abs(dragging[1] - dragging[0]) === 0) {
      return null;
    }
    return `left: ${Math.min(dragging[1], dragging[0]) - rulerBounds.x}px;`
      + ` width: ${Math.abs(dragging[1] - dragging[0])}px`;
  });

  function handleClick(ev) {
    if (!dragging || Math.abs(dragging[1] - dragging[0]) <= 3) {
      playback.seek(percentToOffset(percentFromPointerEvent(ev)));
    }
  }

  function handlePointerDown(ev) {
    if (ev.button !== 0) {
      return;
    }

    ev.preventDefault();
    document.addEventListener('pointerup', handlePointerUp);
    document.addEventListener('pointermove', handlePointerMove);
    dragging = [ev.pageX, ev.pageX];
  }

  function handlePointerMove(ev) {
    if (!rulerEl) {
      return;
    }
    ev.preventDefault();

    rulerBounds = rulerEl.getBoundingClientRect();
    const endDrag = Math.max(rulerBounds.x, Math.min(rulerBounds.x + rulerBounds.width, ev.pageX));
    if (dragging) {
      dragging = [dragging[0], endDrag];
    }
    hoverX = endDrag;
  }

  function handlePointerUp(ev) {
    // prevent preventDefault for back(3) and forward(4) mouse buttons
    if (ev.button !== 3 && ev.button !== 4) {
      ev.preventDefault();
    }

    document.removeEventListener('pointerup', handlePointerUp);
    document.removeEventListener('pointermove', handlePointerMove);
    if (!dragging || !rulerEl) {
      return;
    }
    const drag = dragging;
    dragging = null;

    rulerBounds = rulerEl.getBoundingClientRect();
    const startPercent = (Math.min(drag[0], drag[1]) - rulerBounds.x) / rulerBounds.width;
    const endPercent = (Math.max(drag[0], drag[1]) - rulerBounds.x) / rulerBounds.width;
    const startOffset = Math.round(percentToOffset(startPercent));
    const endOffset = Math.round(percentToOffset(endPercent));

    if (Math.abs(drag[1] - drag[0]) > 3) {
      const offset = playback.currentOffset();
      if (offset < startOffset || offset > endOffset) {
        playback.seek(startOffset);
      }
      onrange?.(route.log_id, startOffset, endOffset);
    } else if (ev.currentTarget !== document) {
      handleClick(ev);
    }
  }

  function handlePointerLeave() {
    hoverX = null;
  }

  $effect(() => {
    if (!thumbnailsEl || typeof ResizeObserver === 'undefined') {
      return;
    }
    const observer = new ResizeObserver((entries) => {
      const entry = entries[0];
      if (!entry) {
        return;
      }
      const { width, height } = entry.contentRect;
      thumbnail = { width, height };
    });
    observer.observe(thumbnailsEl);
    return () => observer.disconnect();
  });

  // The playhead moves every frame, so it is written straight to the DOM
  // instead of going through the reactive graph.
  $effect(() => {
    if (!hasRuler) {
      return;
    }
    let frame = requestAnimationFrame(function tick() {
      frame = requestAnimationFrame(tick);
      if (!rulerRemainingEl || !zoom) {
        return;
      }
      const percent = Math.floor(10000 * offsetToPercent(Math.floor(playback.currentOffset()))) / 100;
      rulerRemainingEl.style.left = `${percent}%`;
      rulerRemainingEl.style.width = `${100 - percent}%`;
    });
    return () => cancelAnimationFrame(frame);
  });

  $effect(() => () => {
    document.removeEventListener('pointerup', handlePointerUp);
    document.removeEventListener('pointermove', handlePointerMove);
  });
</script>

<div class={className}>
  <div role="presentation" class="relative {hasRulerCls}" style="width: 100%">
    <div class="relative left-0 h-[12px] w-full overflow-hidden {hasRulerCls}">
      {#if route && events}
        <div class="absolute h-[12px]" style="background: {DRIVING_BLUE}; {routeStyle}">
          {#each bands as bandStyle, i (i)}
            <div class="absolute inline-block h-[12px]" style={bandStyle}></div>
          {/each}
        </div>
      {/if}
      <div
        class="pointer-events-none absolute top-0 left-0 z-[2] h-[12px] w-full {hasRulerCls}"
        style="background: {STATUS_GRADIENT}"
      ></div>
    </div>

    <div
      bind:this={thumbnailsEl}
      class="h-[20px] w-full overflow-hidden whitespace-nowrap select-none {hasRulerCls}"
    >
      {#if thumbnailsVisible && zoom}
        <Thumbnails {thumbnail} {percentToOffset} currentRoute={route} />
      {/if}
    </div>

    {#if hasRuler}
      <div
        bind:this={rulerEl} {@attach keepTouch()}
        role="presentation"
        class="h-[44px] w-full touch-none"
        style="background-color: rgb(37, 51, 61)"
        onpointerdown={handlePointerDown}
        onpointerup={handlePointerUp}
        onpointermove={handlePointerMove}
        onpointerleave={handlePointerLeave}
      >
        <!-- left/width are set every frame by the effect above, so they cannot come
             from tailwind utilities: this project builds them with !important. -->
        <div
          bind:this={rulerRemainingEl}
          class="pointer-events-none absolute h-[44px] opacity-[0.45]"
          style="left: 0; width: 100%; background-color: rgba(29, 34, 37, 0.9); border-left: 1px solid #D8DDDF"
        ></div>
        {#if draggerStyle}
          <div
            class="pointer-events-none absolute h-[44px]"
            style="background: rgba(255, 255, 255, 0.1); border-left: 1px solid rgba(255, 255, 255, 0.3); border-right: 1px solid rgba(255, 255, 255, 0.3); {draggerStyle}"
          ></div>
        {/if}
      </div>
      {#if hover}
        <div
          class="absolute top-[83px] z-[3] w-[80px] rounded-[14px] border border-white/10 px-[4px] py-[3px] text-center text-[0.7em] text-white"
          style="left: {hover.left}px; background-color: #272c2f"
        >
          {hover.text}
        </div>
      {/if}
    {/if}
  </div>
</div>
